### ISSUE TITLE
오픈소스 관리

### ISSUE THREAD

**Issue by kang0921ok** [kang0921ok/octopus#4]
readme
license
release note

**Comment by JiKyoungHo** [comment]
# **Readme**
### Readme.md 
* 설명 기입
* 디렉토리나 압축파일에 포함된 기타 파일에 대한 정보를 가짐
* 일반적으로 SW와 함께 배포 

### 기본 구성

* news 사용자들이 참고할 체인지 로그 
   * 변경사항에 대한 기록 , 보통 가장 상위에서 포함 -  빠른 문제 해결 도움

* readme 일반정보 

* authors  제작정보

* file list 목록

* computer configuration  구성

* thanks 도와주신 분들 정보

* changelog   프로그래머들이 참고할 자세한 체인지로그

* install  설치 안내

* copying / licence  저작권 및 사용권 정보

* bugs  알려진 버그 , 새로운 버그 보고방법 

### 이 외 확장자 명
* .TXT
*  .md
* .1ST
* .DOC
* .ME

### 사용 도구
* Mark Down
   * 글자 굵기 , 이미지. 삽입, 
   * https://heropy.blog/2017/09/30/markdown/


# **Release Note**
### Release Note
* **변경사항을 기록하고 SW나 Program들이 업데이트등 변화가 생기면 설명해주는 문서**
* 변화를 준 이유를 쉽게 알 수 있다.
* 표준형식은 없다 . 고객에게 있다.
* 명확성
* 제목에는 제품이름 및 버전정보

### Open Release Note
* 릴리스
* 빌드 번호
* 모든 고정 된 공개 버그
* 모든 추가 된 공용 기능

### 품질 관리 릴리스 노트
* 릴리스
* 빌드 번호
* 버그 번호를 포함한 모든 수정 된 버그
* 디자인 문서에 대한 링크를 포함하여 추가 된 모든 기능

### 버전별 정리
* http://www.barebones.com/support/bbedit/archived_notes.html
### 패치별 정리
* https://fetchsoftworks.com/fetch/release-notes

# **License**
### 정의 
* 권리자가 다른 사람에게 일정한 조건으로 특정 행위를 할 수 있는 권한을 부여할 수 있다.
### 참고
* https://github.com/github-tools/github-release-notes/blob/master/LICENSE
* https://project.oss.kr/board/openSouceView.do?board_seq=643

### Open source license
*  https://ko.wikipedia.org/wiki/%EC%98%A4%ED%94%88_%EC%86%8C%EC%8A%A4_%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4
* https://www.olis.or.kr/license/introduction.do;olis_JSESSIONID=689108EC48D86023715A95695B505842

**Comment by JiKyoungHo** [comment]
### Release 만드는 법 
-------
* 1. code 파트에서  release란을 들어간다.

* 2. release를 설정 하게되는데 

* 3. 제목은 버전 정보를 사용한다.

* 4. 패치된 버전을 사용 할 수 있게끔하는 파일을 등록한다.

### 그림 설명 
------
* https://help.github.com/articles/creating-releases/

* https://help.github.com/articles/linking-to-releases/
